using System;

namespace MyAdventureGame
{
    /// <summary>
    /// This class combines the to-be-executed-command and the parsed arguments. 
    /// </summary>
    /// <remarks>
    /// This class is generated by the InputManager after each Prompt call by the Game class in the main loop.
    /// </remarks>
    public class InputResult
    {
        /// <summary>
        /// Initializes a new instance of the class.
        /// </summary>
        /// <param name="command">The command that should be executed.</param>
        /// <param name="args">The arguments that should be passed to the command.</param>
        public InputResult(Command command, string[] args)
        {
            this.Command = command;
            this.Args = args;
        }

        /// <summary>
        /// The command that should be executed.
        /// </summary>
        /// <value>The command.</value>
        public Command Command
        {
            get; private set;
        }

        /// <summary>
        /// The arguments that are passed to the command.
        /// </summary>
        /// <value>The arguments.</value>
        public string[] Args
        {
            get; private set;
        }

        /// <summary>
        /// Execute this command and passes the arguments.
        /// </summary>
        /// <returns>
        /// The output generated by the command.
        /// </returns>
        public string Execute()
        {
            return this.Command.Execute(this.Args);
        }
    }
}

